### PR TITLE
Adding and updating some submission links

### PR DESCRIPTION
**Pull request by karllhughes**
I've been working on a list of [marketing tactics for my side projects](https://github.com/karllhughes/side-project-marketing) and initially I was building a list just like this. Then I decided it was silly to have two lists, so I'd like to merge in some of the sources I had.

I also updated a couple links. Let me know if you have any comments/improvements or if any of the sources I listed are inappropriate.

Thanks for your work compiling this. Great idea!

### CODE REVIEW

**Comment by mmccaff** [comment]
Thanks for the contributions @karllhughes !

It looks like there were a few issues when the PR was validated with Travis - 


```
Issues :-(
> Links 
  1. [L061] 416 https://www.crunchbase.com/app/register  
  2. [L089]  https://makerbase.co/ Connection timed out - connect(2) for "makerbase.co" port 443 
  3. [L094]  http://www.mosaichub.com/ getaddrinfo: Temporary failure in name resolution 
  4. [L125]  http://www.softpedia.com/ Connection timed out - connect(2) for "www.softpedia.com" port 80 
> Dupes 
  1. [L150] http://www.techgreet.com/submit-your-tech-startup/
```

If you can fix these I'll merge the PR later on, otherwise I'll just delete those additions from this PR and merge later.

Thanks again!

Matt

**Comment by karllhughes** [comment]
Oh thanks! I'll update and let you know.

**Comment by karllhughes** [comment]
@mmccaff I updated to working links, but for some reason it keeps saying http://www.startupranking.com/ and https://www.crunchbase.com/#/home/index are failing. I can load those links fine in my browser, so maybe there's something going on with the CI?

Definitely don't want to remove Crunchbase as it's a good place to post. The other site is minor so not as big a deal to drop it.

Let me know if there's anything else I can do or if I'm not doing something right with those links. Thanks again!

**Comment by mmccaff** [comment]
Those last two failures in Travis don't look like real failures; I can also visit those urls fine in a real web browser.

I'd just merge it but then the README won't have the nice green passing badge.  :) I will check if there is a way to omit validating a single line, or retry the build later.

**Pull request merged**
