### PR TITLE
Adding a couple new site suggestions

### PR DESCRIPTION
**Pull request by founderbanger**

### CODE REVIEW

**Comment by rebootcode** [comment]
the Loop doesn't sound like a link to post startup (looks spam)

**Comment by founderbanger** [comment]
It's Loop and it is not spam, many startups have already posted there to get feedback... have you actually looked at it? Check out the front page of the app [](https://app.loopinput.com/) and you will see many featured startups and no spam.

**Comment by mmccaff** [comment]
The Loop looks like a product. "Loop develops visual customer feedback management software, including a screenshot plugin that integrates directly into your website and an embeddable forum to vote on submitted feedback, to help you drive strategic product decisions and catch bugs."

It sounds like a tool - "Loop develops visual customer feedback management software, including a screenshot plugin that integrates directly into your website and an embeddable forum to vote on submitted feedback, to help you drive strategic product decisions and catch bugs."

A startup might use this tool, but it does not look like a place where someone would post their startup to list it for marketing purposes or to get the word out (which is what this is a list of).

Is there a link to somewhere on the loop where a startup can be posted for that purpose?

**Comment by founderbanger** [comment]
> The Loop looks like a product. "Loop develops visual customer feedback management software, including a screenshot plugin that integrates directly into your website and an embeddable forum to vote on submitted feedback, to help you drive strategic product decisions and catch bugs."
> 
> It sounds like a tool - "Loop develops visual customer feedback management software, including a screenshot plugin that integrates directly into your website and an embeddable forum to vote on submitted feedback, to help you drive strategic product decisions and catch bugs."
> 
> A startup might use this tool, but it does not look like a place where someone would post their startup to list it for marketing purposes or to get the word out (which is what this is a list of).
> 
> Is there a link to somewhere on the loop where a startup can be posted for that purpose?

Look at the featured public projects section which also gives a do-follow backlink: https://app.loopinput.com/

**Comment by mmccaff** [comment]
I added the link as https://app.loopinput.com/ and merged the PR

**Pull request merged**
