### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by magusss**

### CODE REVIEW

**Comment by mmccaff** [comment]
This looks like a collection of resources and tools for startups, like live chat, help making logos, etc. 

Is there a place for people to post/promote their startup on this site?

**Comment by magusss** [comment]
Yes, people can submit their SaaS Startups or online tools and they are featured on the site after the review process. Most of the products on the site are tools of Startup companies. So, they can reach out new users if they submit their products. 

By the way, I'm sorry if I had made some mistakes while updating the file. This is my first time using here.

**Comment by mmccaff** [comment]
Haha, I somehow missed the 'Submit' button on the site. I see it now.

I'm merging this in.

Also, you updated the file correctly, no worries.  Thanks for the contribution.

**Comment by magusss** [comment]
Thank you :)

**Pull request merged**
